"""
Init

Revision ID: 7957c7c04ec4
Revises: 
Create Date: 2022-07-08 17:10:53.789533

"""
from alembic import op
import sqlalchemy as sa
import foodlist.models


# revision identifiers, used by Alembic.
revision = '7957c7c04ec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodlist_inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.Text(), nullable=False),
    sa.Column('shopping_notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foodlist_inventories_secret_key'), 'foodlist_inventories', ['secret_key'], unique=False)
    op.create_table('foodlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('temporary_additional_min_quantity', sa.Integer(), nullable=False),
    sa.Column('best_before', sa.Date(), nullable=True),
    sa.Column('expire_warning', sa.Interval(), nullable=True),
    sa.Column('keep_if_zero', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('hidden_on_shopping', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foodlist_items')
    op.drop_index(op.f('ix_foodlist_inventories_secret_key'), table_name='foodlist_inventories')
    op.drop_table('foodlist_inventories')
    # ### end Alembic commands ###
